### ISSUE TITLE
Error in Building the solution from the source code 

### ISSUE THREAD

**Issue by hansSweden** [GeorgeAlexandria/CoCo#15]
I downloaded the source code and I have tried to build it by using MVS 2017, but it gives me the following error: 

**The "GetDeploymentPathFromVisxManifest" task failed unexpectedly ...** 

Is anyone familiar with this error?

**Comment by GeorgeAlexandria** [comment]
It can be due to the settings of the VS for the exp. version. So I can suggest you to reset settings for it and check again. Read [how to reset seetings for VS](https://stackoverflow.com/questions/17203820/how-do-i-truly-reset-every-setting-in-visual-studio-2012/19460071#19460071). 
Firstly just try it for the experimental version. I hope this solve your issue.

**Comment by GeorgeAlexandria** [comment]
Hi, @hansSweden.

In the latest versions of Visual Studio and the CoCo this randomly issue might was fixed. 
So I will close this issue, but if you still have some troubles with building from source code you can reopen current issue or create a new.

Thanks!
