### ISSUE TITLE
Colors not applied in VS 2017 15.7 preview 3 and 4

### ISSUE THREAD

**Issue by mangeg** [GeorgeAlexandria/CoCo#16]
Starting with preview 3 of the 15.7 version of VS 2017 the colorization is no longer working.
It worked as expected in preview 2, but then in preview 3 not longer working. Preview 4 was just released and it has the same problem.

For testing I installed a few other similar extensions and they too seemed to have the same issue.

**Comment by GeorgeAlexandria** [comment]
@mangeg, the preview version of VS often has a few breaking changes for editors formats, You just tried a few other similar extension and found that they too broke.

If I found a some issue on the [vscommunity](https://developercommunity.visualstudio.com/spaces/8/index.html) or solution of it, I will get you know (and, of course, try to fix it), but I think that vs team will fix it faster to the stable realesed version 15.7

P.S. I will be grateful if You can provide a more details:
Does activity log have a some error for extension during startup the vs?
Do editor items show in the fonts and colors option?

**Comment by mangeg** [comment]
Yeah, just wanted to make an issue as a heads up in case they are introducing any breaking changes that will persist to the release version. Don't want to be without colors when it is released 😄 

The link to the VSCommunity page does not link to an issue. Tried to search for any but couldn't find it.

The editor items do show in the fonts and colors options.
Regarding activity log it seems to load without problems

```xml
<entry>
    <record>1197</record>
    <time>2018/04/18 21:47:10.332</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\USERS\MAGNU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_17CDB4DF\EXTENSIONS\qnnwjv4t.nfi\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>1198</record>
    <time>2018/04/18 21:47:10.332</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\USERS\MAGNU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_17CDB4DF\EXTENSIONS\QNNWJV4T.NFI\</path>
  </entry>
<entry>
    <record>1209</record>
    <time>2018/04/18 21:47:10.337</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\MAGNU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_17CDB4DF\EXTENSIONS\QNNWJV4T.NFI\</path>
  </entry>
```
I checked and in the qnnwjv4t.nfi folder the CoCo files are located. Nothing further logged that I could find.

**Comment by mangeg** [comment]
As an update. The issue persists in preview 4.

**Comment by crmagicxxx** [comment]
I can confirm too - VS v15.7.0 breaks custom colors

**Comment by GeorgeAlexandria** [comment]
@arfmach, @crmagicxxx, thanks for your attention. I will investigate this issue as soon as possible. 

Any info about issue would be helpful.

**Comment by arfmach** [comment]
@GeorgeAlexandria, my VS doesn't have any Activity Log. Just to let you know that there's no error message.

**Comment by GeorgeAlexandria** [comment]
@mangeg, @crmagicxxx, @arfmach,
***Good news***: seems that the problem was found and fixed. 
***Not good news_1***: I need more time to test all of cases with a new patch, so you need to wait a several days of patch or can you help to test it taking the pre-release build (or build version by yourself from new sources :) )?
***Not good news_2***: Patch breaks the all saved colors, they will be reset to default values. So resetting wouldn't be fixed, because finish the #3 will be more useful than fixing the resetting.

**Comment by crmagicxxx** [comment]
Hey @GeorgeAlexandria 
I am interested in trying/testing pre-release build. Can you please give me some download link, because I don't know how to build from the source? I want to test how it goes with v15.7

**Comment by GeorgeAlexandria** [comment]
@crmagicxxx, 
If you want try to test pre-release you **Must** save your VS settings or create a backup instance of VS, because I have a few troubles when try to apply some changes to extensions that were installed on my VS and these changes often break my VS that I need to repair it (I don't know what else the VS team ~~broke~~ changed), so I can't yet test installation, updation and deletion CoCo with the patch. But I tested all tests of colorizing that I wanted and it works very well in VS 15.7. 

If you still want to test when you know about a possible troubles but don't know how to create backup of settings or don't know how to install, update vsix from command, line let me know about it.

You can find pre-release version of .vsix in the [here](https://github.com/GeorgeAlexandria/CoCo/files/1988647/CoCo.zip)

**Comment by crmagicxxx** [comment]
@GeorgeAlexandria 
Thanks for the update. Unfortunately, I can't afford myself such scenario, I am in the middle of a very important project. Can't risk losing time on repairing VS :( As soon as I finish this, I'll get back and install pre-release...

**Comment by mangeg** [comment]
I am running the pre-release version, and it works without problem so far in 15.7.1.

**Comment by mangeg** [comment]
The colors were reset back to default.

**Comment by GeorgeAlexandria** [comment]
Check the last version of CoCo for vs15 that should fix this issue. Remember that the colors will be reset back to default values in the last version.

If you have a some issues to install, update or delete extensions (not just CoCo) in the VS, I recommend you to follow [this issue](https://developercommunity.visualstudio.com/content/problem/249077/visual-studio-2017-fresh-installation-i-cant-modif.html) and describe the issue in your case.
