### ISSUE TITLE
Support existing VS elements (class, struct, interface,...)

### ISSUE THREAD

**Issue by laicasaane** [GeorgeAlexandria/CoCo#24]
So we could configure them at one place and much easier (with hex color input).

**Comment by GeorgeAlexandria** [comment]
@laicasaane, Thanks for your feedback.

Actually, I think that it's not good idea to classify types: class, structure, interface and so on, - because the VS colorize this types to easy recognize them. 
Whell, this functionality can be added to extensions and it can be avoided in the options to use the existing in the VS classifications if someone thinks like me, but it isn't a first priority task.

However, if someone else agree with your opinion maybe I'll increase priority and add this feature (or accept MR from community) ).
