### ISSUE TITLE
Add ability to export presets

### ISSUE THREAD

**Issue by laicasaane** [GeorgeAlexandria/CoCo#47]
I've recently reinstalled the VS and must manually reconfig my CoCo presets. As the theme options grow, there should be a way to export and import preset files.

**Comment by GeorgeAlexandria** [comment]
>must manually reconfig my CoCo presets

After updating CoCo automatically upgrade your settings to a new version if it has a something changes, so you actually do not need to change your existing presets, because they must work as is. 

Do you mean that you want extend existing presets with a new custom settings for a new added classifications? If so, you can apply existing preset, set options for a new classifications and save the current state as preset.

Currently CoCo doesn't have a way to export|import settings from UI, but settings are stored in the **%localappdata%\CoCo\CoCo.config** and you can copy|insert presets from it

**Comment by GeorgeAlexandria** [comment]
>This is exactly what I want, just this! No need for a UI function

I got it.

>You should put this in the readme

I will add it into the readme for the next release, or maybe earlier
